#!/usr/bin/env bash
#
# Sets this machine up from scratch.
#
# Everything that differs between macOS and Linux lives in
# script/bootstrap.<platform>; this file only decides which one to run and
# then lays down the symlinks, which are shared.

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLATFORM="$("${BASEDIR}/script/lib/platform")"

cd "${BASEDIR}"

"${BASEDIR}/script/bootstrap.${PLATFORM}"

"${BASEDIR}/script/install"
